# Generated by Django 4.2.16 on 2025-03-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudflare_tunnel_id', models.CharField(max_length=255, verbose_name='CloudFlare Tunnel ID')),
                ('cloudflare_token', models.CharField(max_length=255, verbose_name='CloudFlare Token')),
                ('config_yml_path', models.CharField(max_length=255, verbose_name='Config.yml Path')),
                ('tencent_secret_key', models.CharField(max_length=255, verbose_name='Tencent Cloud SecretKey')),
                ('tencent_secret_id', models.CharField(max_length=255, verbose_name='Tencent Cloud SecretID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
