# Generated by Django 4.2.16 on 2025-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudflare_tunnel_id', models.CharField(max_length=255, verbose_name='CloudFlare Tunnel ID')),
                ('cloudflare_global_api_key', models.CharField(max_length=255, verbose_name='CloudFlare Global API Key')),
                ('cloudflare_email', models.CharField(max_length=255, verbose_name='CloudFlare Email')),
                ('cloudflare_zone_id', models.CharField(max_length=255, verbose_name='CloudFlare Zone ID')),
                ('cloudflared_container_id', models.CharField(max_length=255, verbose_name='CloudFlared Container ID')),
                ('cloudflared_default_behavior', models.CharField(max_length=255, verbose_name='CloudFlared Default Behavior')),
                ('config_yml_path', models.CharField(max_length=255, verbose_name='Config.yml Path')),
                ('tencent_secret_key', models.CharField(max_length=255, verbose_name='Tencent Cloud SecretKey')),
                ('tencent_secret_id', models.CharField(max_length=255, verbose_name='Tencent Cloud SecretID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='DomainConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Domain')),
                ('proxy_pass', models.CharField(max_length=255, verbose_name='Proxy Pass')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='Host')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Domain Configuration',
                'verbose_name_plural': 'Domain Configurations',
            },
        ),
    ]
