# Generated by Django 4.2.16 on 2025-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationmodel',
            name='cloudflare_domain_suffix',
            field=models.CharField(default='cfargotunnel.com', max_length=255, verbose_name='CloudFlare Domain Suffix'),
        ),
    ]
